### ISSUE TITLE
attach_distributed_sequence_column 사용 이슈

### ISSUE THREAD

**Issue by beobest2** [beobest2/spark_study#1]
`attach_distributed_sequence_column` 를 사용하지 않는 경우: 정상 동작

```python
>>> psidx = ps.Index([1, 2, 3, 4, 5])
>>>
>>> scol_name = psidx._internal.index_spark_column_names[0]
>>>
>>> sdf = psidx._internal.spark_frame.select(psidx.spark.column)
>>>
>>> sdf = sdf.select(scol_name)
>>>
>>> sdf.show()
+-----------------+
|__index_level_0__|
+-----------------+
|                1|
|                2|
|                3|
|                4|
|                5|
+-----------------+

>>>
>>> internal = InternalFrame(
...         spark_frame=sdf,
...         index_spark_columns=psidx._internal.index_spark_columns,
...         index_names=psidx._internal.index_names,
...         index_fields=psidx._internal.index_fields
...         )
>>>
>>> ps.DataFrame(internal).index
Int64Index([1, 2, 3, 4, 5], dtype='int64')
```

오류 발생

```python
>>> psidx = ps.Index([1, 2, 3, 4, 5])
>>>
>>> scol_name = psidx._internal.index_spark_column_names[0]
>>>
>>> sdf = psidx._internal.spark_frame.select(psidx.spark.column)
>>>
>>> sdf = InternalFrame.attach_distributed_sequence_column(
...     sdf, column_name="__tmp_column__"
... )
>>>
>>> sdf.show()
+--------------+-----------------+
|__tmp_column__|__index_level_0__|
+--------------+-----------------+
|             0|                1|
|             1|                2|
|             2|                3|
|             3|                4|
|             4|                5|
+--------------+-----------------+

>>>
>>> sdf = sdf.select(scol_name)
>>>
>>> sdf.show()
+-----------------+
|__index_level_0__|
+-----------------+
|                1|
|                2|
|                3|
|                4|
|                5|
+-----------------+

>>>
>>> internal = InternalFrame(
...         spark_frame=sdf,
...         index_spark_columns=psidx._internal.index_spark_columns,
...         index_names=psidx._internal.index_names,
...         index_fields=psidx._internal.index_fields
...         )
>>>
>>> ps.DataFrame(internal).index
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jaden/Desktop/devel/spark_commit/spark/python/pyspark/pandas/frame.py", line 3474, in index
    return Index._new_instance(self)
  File "/Users/jaden/Desktop/devel/spark_commit/spark/python/pyspark/pandas/indexes/base.py", line 188, in _new_instance
    anchor._internal.spark_type_for(anchor._internal.index_spark_columns[0]), IntegralType
  File "/Users/jaden/Desktop/devel/spark_commit/spark/python/pyspark/pandas/internal.py", line 940, in spark_type_for
    return self.spark_frame.select(label_or_scol).schema[0].dataType
  File "/Users/jaden/Desktop/devel/spark_commit/spark/python/pyspark/sql/dataframe.py", line 1685, in select
    jdf = self._jdf.select(self._jcols(*cols))
  File "/Users/jaden/Desktop/devel/spark_commit/spark/python/lib/py4j-0.10.9.2-src.zip/py4j/java_gateway.py", line 1309, in __call__
  File "/Users/jaden/Desktop/devel/spark_commit/spark/python/pyspark/sql/utils.py", line 117, in deco
    raise converted from None
pyspark.sql.utils.AnalysisException: Resolved attribute(s) __index_level_0__#279L missing from __index_level_0__#289L,__natural_order__#307L in operator !Project [__index_level_0__#279L]. Attribute(s) with the same name appear in the operation: __index_level_0__. Please check if the right attribute(s) are used.;
!Project [__index_level_0__#279L]
+- Project [__index_level_0__#289L, monotonically_increasing_id() AS __natural_order__#307L]
   +- Project [__index_level_0__#289L]
      +- LogicalRDD [__tmp_column__#288L, __index_level_0__#289L], false
```

`attach_distributed_sequence_column` 로  `__tmp_column__` 를 붙인 후에 select로 `__index_level_0__` 만 선택한 sdf를 사용했는데 계속 오류

**Comment by beobest2** [comment]
```python
sdf.drop(scol_name)
```
도 동일 오류
`__tmp_column__` 가 계속 나옴

**Comment by beobest2** [comment]
Internal의 `attach_distributed_sequence_column` 구현을 살펴보면 scala의 `withSequenceColumn` 호출

```python
    @staticmethod
    def attach_distributed_sequence_column(sdf: SparkDataFrame, column_name: str) -> SparkDataFrame:
        """
        This method attaches a Spark column that has a sequence in a distributed manner.
        This is equivalent to the column assigned when default index type 'distributed-sequence'.

        >>> sdf = ps.DataFrame(['a', 'b', 'c']).to_spark()
        >>> sdf = InternalFrame.attach_distributed_sequence_column(sdf, column_name="sequence")
        >>> sdf.show()  # doctest: +NORMALIZE_WHITESPACE
        +--------+---+
        |sequence|  0|
        +--------+---+
        |       0|  a|
        |       1|  b|
        |       2|  c|
        +--------+---+
        """
        if len(sdf.columns) > 0:
            return SparkDataFrame(
                sdf._jdf.toDF().withSequenceColumn(column_name),  # type: ignore
                sdf.sql_ctx,
            )
        else:
            cnt = sdf.count()
            if cnt > 0:
                return default_session().range(cnt).toDF(column_name)
            else:
                return default_session().createDataFrame(
                    [], schema=StructType().add(column_name, data_type=LongType(), nullable=False)
                )
```


https://github.com/apache/spark/blob/c6140d4d0af7f34152c1b681110a077be36f4068/sql/core/src/main/scala/org/apache/spark/sql/Dataset.scala#L3543

```scala
  /**
   * It adds a new long column with the name `name` that increases one by one.
   * This is for 'distributed-sequence' default index in pandas API on Spark.
   */
  private[sql] def withSequenceColumn(name: String) = {
    val rdd: RDD[InternalRow] =
      // Checkpoint the DataFrame to fix the partition ID.
      localCheckpoint(false)
      .queryExecution.toRdd.zipWithIndex().mapPartitions { iter =>
      val joinedRow = new JoinedRow
      val unsafeRowWriter =
        new org.apache.spark.sql.catalyst.expressions.codegen.UnsafeRowWriter(1)

      iter.map { case (row, id) =>
        // Writes to an UnsafeRow directly
        unsafeRowWriter.reset()
        unsafeRowWriter.write(0, id)
        joinedRow(unsafeRowWriter.getRow, row)
      }
    }

    sparkSession.internalCreateDataFrame(
      rdd, StructType(StructField(name, LongType, nullable = false) +: schema), isStreaming)
  }

```

**Comment by beobest2** [comment]
아래 오류 메세지를 보니 기존의 `__index_level_0__` 는 뒤에 #279가 붙어서 다른 버전을 가리킴
따라서 인덱스 이름으로 새롭게 컬럼을 만들면됨

```
pyspark.sql.utils.AnalysisException: Resolved attribute(s) __index_level_0__#279L missing from __index_level_0__#289L,__natural_order__#307L in operator !Project [__index_level_0__#279L]. Attribute(s) with the same name appear in the operation: __index_level_0__. Please check if the right attribute(s) are used.;
!Project [__index_level_0__#279L]
+- Project [__index_level_0__#289L, monotonically_increasing_id() AS __natural_order__#307L]
   +- Project [__index_level_0__#289L]
      +- LogicalRDD [__tmp_column__#288L, __index_level_0__#289L], false

```

수정 후

```python
>>> internal = InternalFrame(
...         spark_frame=sdf,
...         index_spark_columns=[
...                 scol_for(sdf, col) for col in psidx._internal.index_spark_column_names
...             ],
...         index_names=psidx._internal.index_names,
...         index_fields=psidx._internal.index_fields
...         )
>>>
>>> ps.DataFrame(internal).index
Int64Index([1, 2, 3, 4, 5], dtype='int64')
```

고민해결~
